
import { PartnerData, PartnerTrack } from "../types";

// NOTE: All partner profiles below are entirely fictional and generated for
// demonstration purposes. Company names, people, and email addresses use the
// reserved `.example.com` domain (RFC 2606) and do not represent real entities.

export const PILOT_PARTNERS: PartnerData[] = [
    {
        agreedToTerms: true,
        contactName: "Alex Carter",
        email: "acarter@skyline.example.com",
        roleTitle: "General Manager",
        roleCategory: "Owner / Executive",
        companyName: "Skyline Systems Inc.",
        website: "www.skyline.example.com",
        hqProvince: ["Ontario (ON)"],
        sellToProvinces: ["Ontario (ON)"],
        sellToUSA: false,
        segmentFocus: "Enterprise (Cross-Industry), SMB (Commercial), Public Sector",
        businessModel: ["Consultancy"],
        industryVerticals: ["Automotive", "Financial Services (FSI)", "Public Sector"],
        publicSectorActive: true,
        publicSectorSegments: ["Federal Govt", "Provincial Govt"],
        publicSectorContracts: "",
        enrolledPrograms: ["Think Big for Small Business", "Well-Architected Partner"],
        competencies: [],
        sdpStatus: ["DynamoDB", "Lambda"],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "<$10k",
        arrGrowthTarget: "50%+",
        cloudCheckrUsage: "Basic — Ad-hoc logins",
        teamSizeSales: "1",
        teamSizeTech: "2-3",
        headcount: { sa: "1-2", delivery: "1-2", dataAi: "1-2", finOps: "0", pm: "0" },
        certCount: { practitioner: "3-4", associate_sa: "1-2", associate_dev: "0", associate_sysops: "0", pro_sa: "3-4", pro_devops: "0", specialty_security: "0", specialty_data: "0", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "No, but I'd like to explore",
        mapFamiliarity: 2,
        mapPhasesDelivered: ["Migrate & Modernization"],
        distributorPsValue: 5,
        distributorPsNeeds: "Additional delivery bandwidth, white-label support",
        buildsAiSolutions: "No, but I'm interested to learn more",
        aiReadinessMatrix: {
            "[Use case] Document understanding": 3,
            "[Use case] Forecasting / personalization": 2,
            "[Service] Amazon Bedrock": 2,
            "[Service] Amazon SageMaker": 3,
            "[Service] Amazon Kendra / OpenSearch": 2
        },
        aiOffersDescription: "N/A",
        aiGtmInterest: "Maybe — need more info",
        provideReferences: false,
        referenceDetails: "",
        aceWinRate: "90",
        aceArrValue: "<$50k",
        demandGenRoutes: ["Partner-led marketing", "Direct outbound"],
        aceUsageMaturity: "Register all opportunities",
        hasSca: false,
        hasPackagedOffers: true,
        packagedOffersDetails: "Security/Compliance, Migration factory setup",
        managedServicesMaturity: 1,
        interestedIn24x7Support: true,
        interestedInMdf: "Yes",
        gtmActivities: ["Marketplace Listing"],
        enablementNeeds: ["Security/Compliance", "Migration factory setup", "Data/AI offers"],
        primaryBusinessContact: { name: "Gabriel Stone", email: "gstone@skyline.example.com" },
        primaryTechContact: { name: "Alex Carter", email: "acarter@skyline.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_B,
        scores: { capability: 45, capacity: 40, growth: 85, ai: 40 }
    },
    {
        agreedToTerms: true,
        contactName: "Jordan Blake",
        email: "jordan.blake@dataforge.example.com",
        roleTitle: "CEO",
        roleCategory: "Owner / Executive",
        companyName: "DataForge Solutions Ltd.",
        website: "www.dataforge.example.com",
        hqProvince: ["Alberta (AB)", "Manitoba (MB)", "Ontario (ON)", "Quebec (QC)"],
        sellToProvinces: ["AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT"],
        sellToUSA: true,
        segmentFocus: "Enterprise, ISV/Tech",
        businessModel: ["MSP"],
        industryVerticals: ["Manufacturing", "Retail", "Hi-Tech", "Games", "Automotive", "Energy & Utilities"],
        publicSectorActive: true,
        publicSectorSegments: ["Provincial Govt", "Municipal Govt", "Higher Ed"],
        publicSectorContracts: "",
        enrolledPrograms: ["Think Big for Small Business", "Well-Architected Partner", "ISV Accelerate", "Immersion Days"],
        competencies: [],
        sdpStatus: ["RDS", "Redshift", "QuickSight"],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "$10k–$50k",
        arrGrowthTarget: "25–50%",
        cloudCheckrUsage: "Proficient — Routine use",
        teamSizeSales: "4-6",
        teamSizeTech: "11+",
        headcount: { sa: "5-7", delivery: "8+", dataAi: "8+", finOps: "2-4", pm: "5-7" },
        certCount: { practitioner: "5+", associate_sa: "3-4", associate_dev: "3-4", associate_sysops: "0", pro_sa: "1-2", pro_devops: "1-2", specialty_security: "0", specialty_data: "5+", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "Yes - we leverage Nimbus Cloud",
        mapFamiliarity: 5,
        mapPhasesDelivered: ["Assess", "Mobilize"],
        distributorPsValue: 5,
        distributorPsNeeds: "White-label within our implementation teams.",
        buildsAiSolutions: "Yes (POC/pilots only)",
        aiReadinessMatrix: {
            "[Use case] RAG on enterprise data": 2,
            "[Use case] Copilots / chatbots": 3,
            "[Use case] Code productivity": 3,
            "[Use case] Document understanding": 4,
            "[Use case] Forecasting / personalization": 4,
            "[Use case] Vision or speech": 4,
            "[Service] Amazon Bedrock": 3,
            "[Model] Third-party ISV AI": 5
        },
        aiOffersDescription: "Accelerators for implementation teams and customers (image processing, analytics).",
        aiGtmInterest: "Yes — want to co-build a plan",
        provideReferences: true,
        referenceDetails: "Multiple high-scale data platform deployments.",
        aceWinRate: "92.86",
        aceArrValue: "$250k–$1M",
        demandGenRoutes: ["Partner-led marketing", "Direct outbound"],
        aceUsageMaturity: "Consistent ACE registration",
        hasSca: false,
        hasPackagedOffers: true,
        packagedOffersDetails: "OverSight - SaaS offering on Marketplace for QuickSight customers.",
        managedServicesMaturity: 5,
        interestedIn24x7Support: true,
        interestedInMdf: "Yes",
        gtmActivities: ["Campaign/ABM"],
        enablementNeeds: ["Certification prep", "Migration factory setup", "Data/AI offers", "Marketplace GTM"],
        primaryBusinessContact: { name: "Jordan Blake", email: "jordan.blake@dataforge.example.com" },
        primaryTechContact: { name: "Riley Nguyen", email: "riley.nguyen@dataforge.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_C,
        scores: { capability: 85, capacity: 100, growth: 75, ai: 72 }
    },
    {
        agreedToTerms: true,
        contactName: "Sam Rivera",
        email: "srivera@beaconit.example.com",
        roleTitle: "CEO",
        roleCategory: "Owner / Executive",
        companyName: "Beacon IT Group",
        website: "www.beaconit.example.com",
        hqProvince: ["British Columbia (BC)"],
        sellToProvinces: ["British Columbia (BC)"],
        sellToUSA: false,
        segmentFocus: "SMB (Commercial)",
        businessModel: ["MSP"],
        industryVerticals: ["Other"],
        publicSectorActive: true,
        publicSectorSegments: ["Municipal Govt", "Nonprofit"],
        publicSectorContracts: "",
        enrolledPrograms: [],
        competencies: [],
        sdpStatus: [],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "<$10k",
        arrGrowthTarget: "<10%",
        cloudCheckrUsage: "I don't know",
        teamSizeSales: "0",
        teamSizeTech: "1",
        headcount: { sa: "1-2", delivery: "0", dataAi: "0", finOps: "0", pm: "0" },
        certCount: { practitioner: "0", associate_sa: "0", associate_dev: "0", associate_sysops: "0", pro_sa: "0", pro_devops: "0", specialty_security: "0", specialty_data: "0", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "No",
        deliversAssessments: "No, but I'd like to explore",
        mapFamiliarity: 1,
        mapPhasesDelivered: [],
        distributorPsValue: 5,
        distributorPsNeeds: "",
        buildsAiSolutions: "No, but I'm interested to learn more",
        aiReadinessMatrix: {},
        aiOffersDescription: "",
        aiGtmInterest: "",
        provideReferences: false,
        referenceDetails: "",
        aceWinRate: "",
        aceArrValue: "",
        demandGenRoutes: [],
        aceUsageMaturity: "",
        hasSca: false,
        hasPackagedOffers: false,
        packagedOffersDetails: "",
        managedServicesMaturity: 1,
        interestedIn24x7Support: true,
        interestedInMdf: "Maybe",
        gtmActivities: [],
        enablementNeeds: [],
        primaryBusinessContact: { name: "Sam Rivera", email: "srivera@beaconit.example.com" },
        primaryTechContact: { name: "Sam Rivera", email: "srivera@beaconit.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_A,
        scores: { capability: 15, capacity: 10, growth: 5, ai: 5 }
    },
    {
        agreedToTerms: true,
        contactName: "Chris Donovan",
        email: "chris.donovan@meridian.example.com",
        roleTitle: "Senior Client Engagement Manager",
        roleCategory: "Sales Leader",
        companyName: "Meridian Consulting",
        website: "www.meridian.example.com",
        hqProvince: ["Ontario (ON)"],
        sellToProvinces: ["Alberta (AB)", "British Columbia (BC)", "Manitoba (MB)", "New Brunswick (NB)", "Newfoundland and Labrador (NL)"],
        sellToUSA: false,
        segmentFocus: "Enterprise, Greenfield, ISV/Tech",
        businessModel: ["MSP"],
        industryVerticals: ["Manufacturing", "Retail", "Hi-Tech", "Financial Services (FSI)", "Other"],
        publicSectorActive: true,
        publicSectorSegments: ["Municipal Govt", "Crown Corps"],
        publicSectorContracts: "",
        enrolledPrograms: ["Think Big for Small Business", "Well-Architected Partner"],
        competencies: [],
        sdpStatus: [],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "$10k–$50k",
        arrGrowthTarget: "10–25%",
        cloudCheckrUsage: "",
        teamSizeSales: "2-3",
        teamSizeTech: "2-3",
        headcount: { sa: "2-4", delivery: "2-4", dataAi: "0", finOps: "0", pm: "2-4" },
        certCount: { practitioner: "0", associate_sa: "1-2", associate_dev: "0", associate_sysops: "0", pro_sa: "1-2", pro_devops: "0", specialty_security: "0", specialty_data: "0", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "No, but I'd like to explore",
        mapFamiliarity: 0,
        mapPhasesDelivered: [],
        distributorPsValue: 5,
        distributorPsNeeds: "",
        buildsAiSolutions: "No, but I'm interested to learn more",
        aiReadinessMatrix: {},
        aiOffersDescription: "",
        aiGtmInterest: "",
        provideReferences: false,
        referenceDetails: "",
        aceWinRate: "",
        aceArrValue: "",
        demandGenRoutes: [],
        aceUsageMaturity: "",
        hasSca: false,
        hasPackagedOffers: false,
        packagedOffersDetails: "",
        managedServicesMaturity: 5,
        interestedIn24x7Support: true,
        interestedInMdf: "Maybe",
        gtmActivities: ["Event Sponsorship"],
        enablementNeeds: [],
        primaryBusinessContact: { name: "Reese Garcia", email: "reese.garcia@meridian.example.com" },
        primaryTechContact: { name: "Amir Hassan", email: "amir.hassan@meridian.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_B,
        scores: { capability: 55, capacity: 50, growth: 60, ai: 10 }
    },
    {
        agreedToTerms: true,
        contactName: "Taylor Brooks",
        email: "taylor.brooks@northwind.example.com",
        roleTitle: "Manager Strategic Partnerships",
        roleCategory: "Alliance",
        companyName: "Northwind Innovations",
        website: "https://northwind.example.com/",
        hqProvince: ["Alberta (AB)", "New Brunswick (NB)", "Nova Scotia (NS)", "Ontario (ON)"],
        sellToProvinces: ["AB", "BC", "MB", "NB", "NL"],
        sellToUSA: false,
        segmentFocus: "Enterprise, SMB, Telco",
        businessModel: ["Consultancy"],
        industryVerticals: ["Retail", "Telco", "Energy & Utilities", "Healthcare", "Public Sector"],
        publicSectorActive: true,
        publicSectorSegments: ["Federal Govt", "Provincial Govt", "Municipal Govt", "Education K-12"],
        publicSectorContracts: "Provincial procurement frameworks (sample)",
        enrolledPrograms: [],
        competencies: [],
        sdpStatus: [],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "<$10k",
        arrGrowthTarget: "Not set",
        cloudCheckrUsage: "None",
        teamSizeSales: "4-6",
        teamSizeTech: "7-10",
        headcount: { sa: "2-4", delivery: "5-7", dataAi: "2-4", finOps: "8+", pm: "3-4" },
        certCount: { practitioner: "5+", associate_sa: "1-2", associate_dev: "0", associate_sysops: "1-2", pro_sa: "0", pro_devops: "1-2", specialty_security: "0", specialty_data: "0", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "Yes - in-house",
        mapFamiliarity: 4,
        mapPhasesDelivered: ["Assess", "Mobilize", "Migrate & Modernize"],
        distributorPsValue: 4,
        distributorPsNeeds: "Delivery bandwidth, scale, and credibility.",
        buildsAiSolutions: "No, but I'm interested to learn more",
        aiReadinessMatrix: {
            "[Use case] RAG on enterprise data": 2,
            "[Use case] Copilots / chatbots": 2
        },
        aiOffersDescription: "Data modernization, advisory, assessment, chatbot POC.",
        aiGtmInterest: "Maybe — need more info",
        provideReferences: false,
        referenceDetails: "Mass notification platform delivered for regional government (sample).",
        aceWinRate: "52.88",
        aceArrValue: ">$1M",
        demandGenRoutes: ["Relationship selling", "Nimbus Cloud referrals", "Partner-led marketing"],
        aceUsageMaturity: "Register all opportunities",
        hasSca: true,
        hasPackagedOffers: false,
        packagedOffersDetails: "",
        managedServicesMaturity: 1,
        interestedIn24x7Support: true,
        interestedInMdf: "Yes",
        gtmActivities: ["Marketplace Listing"],
        enablementNeeds: ["Certification prep"],
        primaryBusinessContact: { name: "Taylor Brooks", email: "taylor.brooks@northwind.example.com" },
        primaryTechContact: { name: "Taylor Brooks", email: "taylor.brooks@northwind.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_C,
        scores: { capability: 70, capacity: 80, growth: 50, ai: 30 }
    },
    {
        agreedToTerms: true,
        contactName: "Jamie Sullivan",
        email: "jamie@summitsoftware.example.com",
        roleTitle: "President",
        roleCategory: "Owner / Executive",
        companyName: "Summit Software Inc.",
        website: "https://www.summitsoftware.example.com",
        hqProvince: ["Ontario (ON)"],
        sellToProvinces: ["AB", "BC", "MB", "ON", "QC", "SK"],
        sellToUSA: false,
        segmentFocus: "Enterprise, Greenfield, ISV/Tech",
        businessModel: ["SI / GSI"],
        industryVerticals: ["Manufacturing", "Hi-Tech", "Automotive", "Energy & Utilities", "ISV / Software"],
        publicSectorActive: false,
        publicSectorSegments: [],
        publicSectorContracts: "",
        enrolledPrograms: ["Think Big for Small Business"],
        competencies: [],
        sdpStatus: [],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "No",
        monthlyResale: "<$10k",
        arrGrowthTarget: "10–25%",
        cloudCheckrUsage: "Basic — Ad-hoc logins",
        teamSizeSales: "2-3",
        teamSizeTech: "7-10",
        headcount: { sa: "1-2", delivery: "2-4", dataAi: "2-4", finOps: "0", pm: "1-2" },
        certCount: { practitioner: "3-4", associate_sa: "1-2", associate_dev: "0", associate_sysops: "0", pro_sa: "0", pro_devops: "0", specialty_security: "0", specialty_data: "0", specialty_ml: "0", specialty_db: "0", specialty_net: "0", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "Yes - leverage Nimbus Cloud",
        mapFamiliarity: 3,
        mapPhasesDelivered: ["Assess", "Mobilize", "Migrate & Modernize"],
        distributorPsValue: 3,
        distributorPsNeeds: "",
        buildsAiSolutions: "Yes (production workloads)",
        aiReadinessMatrix: {
            "[Use case] RAG on enterprise data": 3,
            "[Use case] Code productivity": 3,
            "[Use case] Document understanding": 3,
            "[Service] Amazon Bedrock": 3,
            "[Service] Amazon SageMaker": 3,
            "[Model] Foundation models via Bedrock": 3,
            "[Model] Classical ML on SageMaker": 1
        },
        aiOffersDescription: "",
        aiGtmInterest: "Maybe — need more info",
        provideReferences: false,
        referenceDetails: "",
        aceWinRate: "88.89",
        aceArrValue: "<$50k",
        demandGenRoutes: ["referrals", "Partner-led marketing"],
        aceUsageMaturity: "Register all opportunities",
        hasSca: false,
        hasPackagedOffers: false,
        packagedOffersDetails: "",
        managedServicesMaturity: 3,
        interestedIn24x7Support: true,
        interestedInMdf: "Yes",
        gtmActivities: ["Case Study"],
        enablementNeeds: ["Data/AI offers", "Marketplace GTM"],
        primaryBusinessContact: { name: "Jamie Sullivan", email: "jamie@summitsoftware.example.com" },
        primaryTechContact: { name: "Jamie Sullivan", email: "jamie@summitsoftware.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_B,
        scores: { capability: 65, capacity: 60, growth: 55, ai: 85 }
    },
    {
        agreedToTerms: true,
        contactName: "Morgan Reed",
        email: "morgan.reed@apexdata.example.com",
        roleTitle: "VP & Head, Managed Services",
        roleCategory: "Global Head Managed Services",
        companyName: "Apex Data Corporation",
        website: "https://apexdata.example.com/",
        hqProvince: ["Ontario (ON)"],
        sellToProvinces: ["AB", "BC", "MB", "NB", "NL", "NS", "ON", "QC", "SK"],
        sellToUSA: true,
        segmentFocus: "Enterprise, ISV/Tech",
        businessModel: ["MSP"],
        industryVerticals: ["Manufacturing", "Retail", "Telco", "Media", "Automotive"],
        publicSectorActive: true,
        publicSectorSegments: ["None of above"],
        publicSectorContracts: "Enterprise pension plan modernization (sample)",
        enrolledPrograms: ["Immersion Days"],
        competencies: ["Migration", "DevOps", "Data & Analytics", "Machine Learning", "Retail", "Generative AI"],
        sdpStatus: ["Redshift", "Glue", "QuickSight"],
        pursuingResale: "Yes",
        resaleAssistanceNeeded: "",
        monthlyResale: "$50k–$200k",
        arrGrowthTarget: "50%+",
        cloudCheckrUsage: "Very well-versed — Core to our ops: partner billing/invoicing.",
        teamSizeSales: "11+",
        teamSizeTech: "11+",
        headcount: { sa: "8+", delivery: "8+", dataAi: "8+", finOps: "8+", pm: "8+" },
        certCount: { practitioner: "5+", associate_sa: "5+", associate_dev: "5+", associate_sysops: "3-4", pro_sa: "5+", pro_devops: "5+", specialty_security: "3-4", specialty_data: "5+", specialty_ml: "5+", specialty_db: "1-2", specialty_net: "1-2", specialty_sap: "0" },
        iacExperience: "Yes",
        deliversAssessments: "Yes - in-house",
        mapFamiliarity: 5,
        mapPhasesDelivered: ["Assess", "Mobilize", "Migrate & Modernize"],
        distributorPsValue: 4,
        distributorPsNeeds: "White label Optimization and Licensing Assessments (OLA)",
        buildsAiSolutions: "Yes (production workloads)",
        aiReadinessMatrix: {
            "[Use case] RAG on enterprise data": 3,
            "[Use case] Copilots / chatbots": 3,
            "[Use case] Code productivity": 3,
            "[Use case] Document understanding": 3,
            "[Service] Amazon Bedrock": 3,
            "[Service] Amazon SageMaker": 3,
            "[Model] Foundation models via Bedrock": 3
        },
        aiOffersDescription: "Agentic AI on AWS, Data & AI Governance, Managed Services Provider.",
        aiGtmInterest: "Yes — want to co-build a plan",
        provideReferences: true,
        referenceDetails: "Major health sector migration and data modernization success stories (sample).",
        aceWinRate: "30",
        aceArrValue: ">$1M",
        demandGenRoutes: ["AWS co-sell referrals", "Partner-led marketing"],
        aceUsageMaturity: "Consistent ACE registration",
        hasSca: true,
        hasPackagedOffers: true,
        packagedOffersDetails: "AI Days, Agentic AI, Data Quality Analysis.",
        managedServicesMaturity: 5,
        interestedIn24x7Support: true,
        interestedInMdf: "Yes",
        gtmActivities: ["Event Sponsorship", "Marketplace GTM"],
        enablementNeeds: ["Marketplace GTM"],
        primaryBusinessContact: { name: "Morgan Reed", email: "morgan.reed@apexdata.example.com" },
        primaryTechContact: { name: "Casey Lin", email: "casey.lin@apexdata.example.com" },
        opportunities: [],
        calculatedTrack: PartnerTrack.TRACK_C,
        scores: { capability: 95, capacity: 100, growth: 90, ai: 60 }
    }
];
